// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFEdJ0lNoeFzDIKIo80uXAh1ozZHXGXOo',
    appId: '1:754011355051:web:5b5cb8710dd4a5fa89c4ee',
    messagingSenderId: '754011355051',
    projectId: 'todonebu',
    authDomain: 'todonebu.firebaseapp.com',
    storageBucket: 'todonebu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv3oga7jbbb8UMky975fuGsqECXPnVggI',
    appId: '1:754011355051:android:54ef65b45bba36f189c4ee',
    messagingSenderId: '754011355051',
    projectId: 'todonebu',
    storageBucket: 'todonebu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlaRg6Rq_WAEFlTE7eCjdJ93hZtQAotOI',
    appId: '1:754011355051:ios:8e9f38175040230b89c4ee',
    messagingSenderId: '754011355051',
    projectId: 'todonebu',
    storageBucket: 'todonebu.firebasestorage.app',
    iosBundleId: 'com.example.todonebu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlaRg6Rq_WAEFlTE7eCjdJ93hZtQAotOI',
    appId: '1:754011355051:ios:8e9f38175040230b89c4ee',
    messagingSenderId: '754011355051',
    projectId: 'todonebu',
    storageBucket: 'todonebu.firebasestorage.app',
    iosBundleId: 'com.example.todonebu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFEdJ0lNoeFzDIKIo80uXAh1ozZHXGXOo',
    appId: '1:754011355051:web:f6ded3bcf01be72789c4ee',
    messagingSenderId: '754011355051',
    projectId: 'todonebu',
    authDomain: 'todonebu.firebaseapp.com',
    storageBucket: 'todonebu.firebasestorage.app',
  );
}
